name: 'Send Teams Notification'
description: 'Sends an Adaptive Card notification to Microsoft Teams'

inputs:
  webhook_url:
    description: 'Microsoft Teams webhook URL'
    required: true
  title:
    description: 'Notification title'
    required: true
  message:
    description: 'Notification message'
    required: true
  color:
    description: 'Card color (Attention, Good, Warning, Default)'
    required: false
    default: 'Default'
  changed_files:
    description: 'List of changed files to display'
    required: false
    default: ''
  link_url:
    description: 'URL to link to (e.g., commit, release)'
    required: false
    default: ''
  link_text:
    description: 'Link button text'
    required: false
    default: 'View Changes'

runs:
  using: 'composite'
  steps:
    - name: Prepare card payload
      id: payload
      shell: bash
      run: |
        # Map color names to hex values
        case "${{ inputs.color }}" in
          "Attention"|"attention") color="Attention" ;;
          "Good"|"good") color="Good" ;;
          "Warning"|"warning") color="Warning" ;;
          *) color="Default" ;;
        esac
        
        # Build facts array for changed files
        facts=""
        if [ -n "${{ inputs.changed_files }}" ]; then
          IFS=',' read -ra files <<< "${{ inputs.changed_files }}"
          for file in "${files[@]}"; do
            facts+=",{\"title\":\"Changed\",\"value\":\"${file}\"}"
          done
          facts="${facts:1}" # Remove leading comma
        fi
        
        # Build action buttons
        actions=""
        if [ -n "${{ inputs.link_url }}" ]; then
          actions="\"actions\":[{\"type\":\"Action.OpenUrl\",\"title\":\"${{ inputs.link_text }}\",\"url\":\"${{ inputs.link_url }}\"}],"
        fi
        
        # Create JSON payload
        cat > payload.json <<EOF
        {
          "type": "message",
          "attachments": [{
            "contentType": "application/vnd.microsoft.card.adaptive",
            "content": {
              "type": "AdaptiveCard",
              "body": [{
                "type": "TextBlock",
                "size": "Large",
                "weight": "Bolder",
                "text": "${{ inputs.title }}"
              },{
                "type": "TextBlock",
                "text": "${{ inputs.message }}",
                "wrap": true
              }${facts:+,{\"type\":\"FactSet\",\"facts\":[$facts]}}],
              ${actions}
              "\$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
              "version": "1.4",
              "msteams": {
                "width": "Full"
              }
            }
          }]
        }
        EOF
        
        cat payload.json

    - name: Send to Teams
      shell: bash
      run: |
        curl -H "Content-Type: application/json" \
             -d @payload.json \
             "${{ inputs.webhook_url }}"
