name: 'Send Teams Message'
description: 'Sends a simple Microsoft Teams notification'

inputs:
  webhook_url:
    description: 'Microsoft Teams webhook URL'
    required: true
  title:
    description: 'Title of the notification'
    required: true
  message:
    description: 'Main message to display'
    required: true
  color:
    description: 'Color accent for the card (Accent, Good, Warning, Attention)'
    required: false
    default: 'Accent'
  show_files:
    description: 'Whether to show changed files list'
    required: false
    default: 'false'
  changed_files:
    description: 'List of changed files'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Send Teams notification
      shell: bash
      run: |
        set -e
        
        WEBHOOK_URL="${{ inputs.webhook_url }}"
        TITLE="${{ inputs.title }}"
        MESSAGE="${{ inputs.message }}"
        COLOR="${{ inputs.color }}"
        SHOW_FILES="${{ inputs.show_files }}"
        FILES="${{ inputs.changed_files }}"
        
        # Validate webhook
        if [ -z "$WEBHOOK_URL" ]; then
          echo "❌ Missing webhook_url"
          exit 1
        fi
        
        # Map color to Teams theme color
        case "$COLOR" in
          Good) THEME_COLOR="00FF00" ;;
          Warning) THEME_COLOR="FFA500" ;;
          Attention) THEME_COLOR="FF0000" ;;
          *) THEME_COLOR="0078D4" ;;
        esac
        
        # Build files section
        FILES_TEXT=""
        if [ "$SHOW_FILES" = "true" ] && [ -n "$FILES" ]; then
          FILES_TEXT="\n\n**Files Changed:**\n\`\`\`\n${FILES}\n\`\`\`"
        fi
        
        # Simple JSON payload (MessageCard format - simpler than Adaptive Cards)
        cat > /tmp/payload.json <<EOF
        {
          "@type": "MessageCard",
          "@context": "https://schema.org/extensions",
          "themeColor": "${THEME_COLOR}",
          "title": "${TITLE}",
          "text": "${MESSAGE}${FILES_TEXT}",
          "sections": [
            {
              "facts": [
                {
                  "name": "Repository:",
                  "value": "${{ github.repository }}"
                },
                {
                  "name": "Branch:",
                  "value": "${{ github.ref_name }}"
                },
                {
                  "name": "Commit:",
                  "value": "${{ github.sha }}"
                },
                {
                  "name": "By:",
                  "value": "${{ github.actor }}"
                }
              ]
            }
          ],
          "potentialAction": [
            {
              "@type": "OpenUri",
              "name": "View Commit",
              "targets": [
                {
                  "os": "default",
                  "uri": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
                }
              ]
            }
          ]
        }
        EOF
        
        # Send to Teams
        echo "📤 Sending notification to Microsoft Teams..."
        
        HTTP_CODE=$(curl -s -o /tmp/response.txt -w "%{http_code}" \
          -H "Content-Type: application/json" \
          -d @/tmp/payload.json \
          "$WEBHOOK_URL")
        
        if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "202" ]; then
          echo "✅ Teams notification sent successfully!"
        else
          echo "❌ Teams webhook failed (HTTP $HTTP_CODE)"
          echo "Response:"
          cat /tmp/response.txt
          exit 1
        fi
