name: 'Send Teams Message'
description: 'Sends a minimal Microsoft Teams notification'

inputs:
  webhook_url:
    description: 'Microsoft Teams webhook URL'
    required: true
  title:
    description: 'Title of the message (optional)'
    required: false
  message:
    description: 'Message to display'
    required: true
  color:
    description: 'Color (optional)'
    required: false
  show_files:
    description: 'Show changed files (optional)'
    required: false
  changed_files:
    description: 'List of changed files (optional)'
    required: false
  link_url:
    description: 'URL for more details (e.g. commit or release link)'
    required: false


runs:
  using: "composite"
  steps:
    - name: Send Teams Adaptive Card
      shell: bash
      run: |
        bash "${{ github.action_path }}/send-teams-message.sh" \
          "${{ inputs.webhook_url }}" \
          "${{ inputs.title }}" \
          "${{ inputs.message }}" \
          "${{ inputs.color }}" \
          "${{ inputs.show_files }}" \
          "${{ inputs.changed_files }}" \
          "${{ inputs.link_url }}"
