name: "Send Microsoft Teams Message"
description: "Sends a simple text message to a Teams channel"

inputs:
  webhook_url:
    description: "Microsoft Teams webhook URL"
    required: true
  message:
    description: "Message text to send"
    required: true

runs:
  using: "composite"
  steps:
    - name: Send Teams message
      shell: bash
      run: |
        echo "📢 Sending message to Teams..."
        curl -s -H 'Content-Type: application/json' \
          -d "{\"text\": \"${{ inputs.message }}\"}" \
          "${{ inputs.webhook_url }}"
        echo "✅ Teams message sent."
