name: 'Send Teams Message'
description: 'Sends a minimal Microsoft Teams notification'

inputs:
  webhook_url:
    description: 'Microsoft Teams webhook URL'
    required: true
  title:
    description: 'Title of the message (optional)'
    required: false
  message:
    description: 'Message to display'
    required: true
  color:
    description: 'Color (optional)'
    required: false
  show_files:
    description: 'Show changed files (optional)'
    required: false
  changed_files:
    description: 'List of changed files (optional)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Send minimal Teams notification
      shell: bash
      run: |
        echo "Test"
