name: 'Send Teams Message'
description: 'Sends a minimal Microsoft Teams notification'

inputs:
  webhook_url:
    description: 'Microsoft Teams webhook URL'
    required: true
  title:
    description: 'Title of the message (optional)'
    required: false
  message:
    description: 'Message to display'
    required: true
  color:
    description: 'Color (optional)'
    required: false
  show_files:
    description: 'Show changed files (optional)'
    required: false
  changed_files:
    description: 'List of changed files (optional)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Send minimal Teams notification
      shell: bash
      run: |
        set -e

        WEBHOOK="${{ inputs.webhook_url }}"
        MSG="${{ inputs.message }}"

        if [ -z "$WEBHOOK" ]; then
          echo "❌ Missing webhook_url"
          exit 1
        fi

        # Optional: escape quotes in message
        SAFE_MSG=$(echo "$MSG" | sed 's/"/\\"/g')

        # Create minimal payload JSON
        cat > /tmp/payload.json <<EOF
{
  "@type": "MessageCard",
  "@context": "http://schema.org/extensions",
  "summary": "Notification",
  "text": "${SAFE_MSG}"
}
EOF

        echo "📋 Payload preview:"
        cat /tmp/payload.json

        # Send payload to Teams
        HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
          -H "Content-Type: application/json" \
          -d @/tmp/payload.json \
          "$WEBHOOK")

        if [ "$HTTP_CODE" = "200" ]; then
          echo "✅ Teams notification sent!"
        else
          echo "❌ Failed with HTTP $HTTP_CODE"
          exit 1
        fi
