name: Release File Watcher

on:
  workflow_call:
    inputs:
      watched_files:
        description: 'Files to watch (one per line or comma-separated)'
        required: true
        type: string
      notification_title:
        description: 'Teams notification title'
        required: true
        type: string
      notification_message:
        description: 'Teams notification message'
        required: true
        type: string
      card_color:
        description: 'Card color (Attention, Good, Warning, Default)'
        required: false
        type: string
        default: 'Default'
      link_url:
        description: 'URL to link to'
        required: false
        type: string
        default: ''
      link_text:
        description: 'Link button text'
        required: false
        type: string
        default: 'View Changes'
    secrets:
      teams_webhook_url:
        description: 'Microsoft Teams webhook URL'
        required: true

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      files_changed: ${{ steps.check.outputs.files_changed }}
      changed_files_list: ${{ steps.check.outputs.changed_files_list }}
    steps:
      - name: Checkout calling repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get previous release tag
        id: prev_tag
        run: |
          current_tag="${{ github.event.release.tag_name }}"
          prev_tag=$(git tag --sort=-creatordate | grep -v "^${current_tag}$" | head -n1)
          echo "prev_tag=$prev_tag" >> $GITHUB_OUTPUT
          echo "Previous tag: $prev_tag"

      - name: Checkout actions library
        uses: actions/checkout@v4
        with:
          repository: m-nikolovska-mak-system/reusable-actions-library
          ref: main
          path: .github/actions-lib

      - name: Check file changes
        id: check
        uses: ./.github/actions-lib/actions/check-file-changes
        with:
          watched_files: ${{ inputs.watched_files }}
          base_ref: ${{ steps.prev_tag.outputs.prev_tag }}
          head_ref: ${{ github.event.release.tag_name }}

  notify:
    needs: check-changes
    if: needs.check-changes.outputs.files_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions library
        uses: actions/checkout@v4
        with:
          repository: m-nikolovska-mak-system/reusable-actions-library
          ref: main

      - name: Send Teams notification
        uses: ./actions/send-teams-message
        with:
          webhook_url: ${{ secrets.teams_webhook_url }}
          title: ${{ inputs.notification_title }}
          message: ${{ inputs.notification_message }}
          color: ${{ inputs.card_color }}
          changed_files: ${{ needs.check-changes.outputs.changed_files_list }}
          link_url: ${{ inputs.link_url }}
          link_text: ${{ inputs.link_text }}
